pool:
  name: 'Hosted VS2017'

steps:
  - checkout: self
    clean: true

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.7.1

  - task: NuGetCommand@2
    inputs:
      command: restore
      includeNuGetOrg: true

  - task: MSBuild@1
    inputs:
      solution: AzureTableStorage.Emulator.InMemory.sln
      configuration: Release
      platform: 'Any CPU'
      msbuildArguments: /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: AzureTableStorage.Emulator 